name: test Ubuntu
on: [push, pull_request]
jobs:
    test:
      strategy:
        matrix:
          name: [Ubuntu-20.04, Ubuntu-22.04]
          include:
            - name: Ubuntu-20.04
              version: ubuntu-20.04
              image: ubuntu20
            - name: Ubuntu-22.04
              version: ubuntu-22.04
              image: ubuntu22
      runs-on: ${{ matrix.version }}
      container: dcodoni/lib:${{ matrix.image }}
      steps:
        - uses: actions/checkout@v3
        - name: Build svZeroDSolver
          shell: bash
          run: |
            conda init
            source /conda/etc/profile.d/conda.sh
            conda activate svfsiplus
            git clone https://github.com/SimVascular/svZeroDSolver.git
            cd svZeroDSolver
            mkdir build
            cd build
            cmake ..
            make -j2